name: PanIndex Release
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  release:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.18]
    name: PanIndex Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: dev
      - name: Build PanIndex
        - uses: libsgh/PanIndex-build-action@main
        - uses: actions/upload-artifact@v2
            with:
              name: PanIndex-artifact
              path: /home/runner/work/PanIndex/PanIndex/dist/compress/*